apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-api
  template:
    metadata:
      labels:
        app: patient-api
    spec:
      containers:
      - name: patient-api
        image: patient-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"
